# Generated by Django 3.2.4 on 2021-06-17 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('proveedor', models.CharField(max_length=100)),
                ('ctr', models.IntegerField(max_length=50)),
                ('producto', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('um', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=15)),
                ('carga', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('eta', models.CharField(max_length=20)),
                ('retiro', models.CharField(max_length=20)),
                ('hora', models.CharField(max_length=20)),
                ('siglaCtr', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
