# Generated by Django 3.2.4 on 2021-07-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embarques', '0002_alter_embarque_ctr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarque',
            name='author',
        ),
    ]
